name: "setup-packer"
description: "Install a specified Packer version on the runner"
inputs:
  version:
    description: "Packer version to install (e.g. 1.10.0 or latest)"
    required: false
    default: "1.10.0"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip curl jq

    - name: Download and install packer
      shell: bash
      run: |
        set -eux
        VERSION="${{ inputs.version }}"
        if [ "$VERSION" = "latest" ]; then
          VERSION="$(curl -fsSL https://checkpoint-api.hashicorp.com/v1/check/packer | jq -r .current_version)"
        fi
        URL="https://releases.hashicorp.com/packer/${VERSION}/packer_${VERSION}_linux_amd64.zip"
        curl -fsSL -o packer.zip "$URL"
        TMPDIR="$(mktemp -d)"
        unzip -o packer.zip -d "$TMPDIR"
        sudo mv -f "$TMPDIR/packer" /usr/local/bin/packer
        rm -rf "$TMPDIR" packer.zip

    - name: Verify packer
      shell: bash
      run: |
        packer version
